# Generated by Django 5.0 on 2024-03-11 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIFictioneer', '0003_ontology_remove_prompt_json_structure_example_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ontology',
            options={'verbose_name_plural': 'Ontologies'},
        ),
    ]
