# Generated by Django 5.0 on 2024-03-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIFictioneer', '0005_alter_ontology_json_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='ontology',
            name='ttl_definition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ontology',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
