# Generated by Django 5.0 on 2024-04-07 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIFictioneer', '0008_ontology_narrative_coherence_structure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ontology',
            old_name='description',
            new_name='narrative_structure_details',
        ),
    ]
