# Generated by Django 5.0 on 2024-04-08 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIFictioneer', '0009_rename_description_ontology_narrative_structure_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ontology',
            old_name='narrative_coherence_structure',
            new_name='coherence_analysis_output_structure',
        ),
    ]
