# Generated by Django 5.0 on 2024-05-26 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIFictioneer', '0011_rename_narrative_structure_details_ontology_ontology_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ontology',
            old_name='narrative_structure',
            new_name='narrative_space_structure',
        ),
    ]
