# Generated by Django 5.0 on 2024-05-26 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIFictioneer', '0012_rename_narrative_structure_ontology_narrative_space_structure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ontology',
            old_name='ontology_description',
            new_name='narrative_space_structure_description',
        ),
    ]
