# Generated by Django 5.0 on 2024-05-28 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIFictioneer', '0013_rename_ontology_description_ontology_narrative_space_structure_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='ontology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts', to='AIFictioneer.ontology'),
        ),
    ]
