# Generated by Django 5.0 on 2024-06-01 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIFictioneer', '0014_alter_prompt_ontology'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ontology',
            old_name='narrative_space_structure',
            new_name='protostory_structure',
        ),
        migrations.RemoveField(
            model_name='ontology',
            name='narrative_space_structure_description',
        ),
    ]
