# Generated by Django 5.0 on 2024-06-01 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIFictioneer', '0015_rename_narrative_space_structure_ontology_protostory_structure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ontology',
            old_name='protostory_structure',
            new_name='protostory_template',
        ),
    ]
